FROM node:8.9.2

# use nodemon for development
RUN npm install --global nodemon

# use cached layer for node modules
COPY ./api/package*.json /tmp/
RUN cd /tmp && npm install
RUN mkdir -p /usr/src/app && cp -a /tmp/node_modules /usr/src/app

# add project files
WORKDIR /usr/src/app
#ADD ./api /usr/src/app

EXPOSE 3000